version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "website-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-135vxbupjl6y9"
s3_prefix = "website-2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DomainName=\"dianalachami\" IndexDocument=\"index.html\""
